/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_s1products_midi_MidiReceiver */

#ifndef _Included_info_s1products_midi_MidiReceiver
#define _Included_info_s1products_midi_MidiReceiver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     info_s1products_midi_MidiReceiver
 * Method:    jni_initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_info_s1products_midi_MidiReceiver_jni_1initialize
  (JNIEnv *, jobject);

/*
 * Class:     info_s1products_midi_MidiReceiver
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_info_s1products_midi_MidiReceiver_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     info_s1products_midi_MidiReceiver
 * Method:    jni_setReceiver
 * Signature: (Linfo/s1products/midi/MidiReceiver;)V
 */
JNIEXPORT void JNICALL Java_info_s1products_midi_MidiReceiver_jni_1setReceiver
  (JNIEnv *, jobject, jobject);

/*
 * Class:     info_s1products_midi_MidiReceiver
 * Method:    jni_open
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_info_s1products_midi_MidiReceiver_jni_1open
  (JNIEnv *, jobject, jint);

/*
 * Class:     info_s1products_midi_MidiReceiver
 * Method:    jni_close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_info_s1products_midi_MidiReceiver_jni_1close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
