/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_s1products_midi_NativeDeviceUtil */

#ifndef _Included_info_s1products_midi_NativeDeviceUtil
#define _Included_info_s1products_midi_NativeDeviceUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     info_s1products_midi_NativeDeviceUtil
 * Method:    jni_initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_info_s1products_midi_NativeDeviceUtil_jni_1initialize
  (JNIEnv *, jobject);

/*
 * Class:     info_s1products_midi_NativeDeviceUtil
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_info_s1products_midi_NativeDeviceUtil_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     info_s1products_midi_NativeDeviceUtil
 * Method:    jni_getOutDeviceCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_info_s1products_midi_NativeDeviceUtil_jni_1getOutDeviceCount
  (JNIEnv *, jobject);

/*
 * Class:     info_s1products_midi_NativeDeviceUtil
 * Method:    jni_getOutDeviceName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_info_s1products_midi_NativeDeviceUtil_jni_1getOutDeviceName
  (JNIEnv *, jobject, jint);

/*
 * Class:     info_s1products_midi_NativeDeviceUtil
 * Method:    jni_getOutDeviceManufacturer
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_info_s1products_midi_NativeDeviceUtil_jni_1getOutDeviceManufacturer
  (JNIEnv *, jobject, jint);

/*
 * Class:     info_s1products_midi_NativeDeviceUtil
 * Method:    jni_getInDeviceCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_info_s1products_midi_NativeDeviceUtil_jni_1getInDeviceCount
  (JNIEnv *, jobject);

/*
 * Class:     info_s1products_midi_NativeDeviceUtil
 * Method:    jni_getInDeviceName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_info_s1products_midi_NativeDeviceUtil_jni_1getInDeviceName
  (JNIEnv *, jobject, jint);

/*
 * Class:     info_s1products_midi_NativeDeviceUtil
 * Method:    jni_getInDeviceManufacturer
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_info_s1products_midi_NativeDeviceUtil_jni_1getInDeviceManufacturer
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
