/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_s1products_midi_NativeTransmitter */

#ifndef _Included_info_s1products_midi_NativeTransmitter
#define _Included_info_s1products_midi_NativeTransmitter
#ifdef __cplusplus
extern "C" {
#endif
#undef info_s1products_midi_NativeTransmitter_SYSEX_PREFIX
#define info_s1products_midi_NativeTransmitter_SYSEX_PREFIX 240L
/*
 * Class:     info_s1products_midi_NativeTransmitter
 * Method:    jni_initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_info_s1products_midi_NativeTransmitter_jni_1initialize
  (JNIEnv *, jobject);

/*
 * Class:     info_s1products_midi_NativeTransmitter
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_info_s1products_midi_NativeTransmitter_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     info_s1products_midi_NativeTransmitter
 * Method:    jni_setTransmitter
 * Signature: (Linfo/s1products/midi/NativeTransmitter;)V
 */
JNIEXPORT void JNICALL Java_info_s1products_midi_NativeTransmitter_jni_1setTransmitter
  (JNIEnv *, jobject, jobject);

/*
 * Class:     info_s1products_midi_NativeTransmitter
 * Method:    jni_open
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_info_s1products_midi_NativeTransmitter_jni_1open
  (JNIEnv *, jobject, jint);

/*
 * Class:     info_s1products_midi_NativeTransmitter
 * Method:    jni_close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_info_s1products_midi_NativeTransmitter_jni_1close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
